In [1]:
import pathlib

In [2]:
data_dir = pathlib.Path('.')
data_dir

WindowsPath('.')

In [3]:
# list(data_dir.glob('*/*.jpg'))

In [4]:
# list_0 = list(data_dir.glob('0/*.jpg'))
# list_0 

In [5]:
import cv2

In [6]:
# img = cv2.imread(str(list_0[0]))

In [7]:
# import matplotlib.pyplot as plt
# plt.imshow(img)

In [8]:
# img.shape

In [9]:
# gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
# plt.imshow(gray_img)

In [10]:
# ret, thresh = cv2.threshold(gray_img, 140, 255, 0)
# plt.imshow(thresh)

In [11]:
# thresh.shape

In [12]:
x = []
y = []
for i in range(10):
    for path in list(data_dir.glob(f'{i}/*.jpg')):
        img = cv2.imread(str(path))
        gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
        ret, thresh = cv2.threshold(gray_img, 140, 255, 0)
        x.append(thresh)
        y.append(i)
x , y

([array([[255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         ...,
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
  array([[255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         ...,
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
  array([[255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         ...,
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
  array([[255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255,

In [13]:
# plt.imshow(x[-2])

In [14]:
# x_flattened = [img.flatten() for img in x ]

In [15]:
# x_flattened

In [16]:
# from sklearn.ensemble import RandomForestClassifier
# clf = RandomForestClassifier(max_depth=3, random_state=0)
# clf.fit(x_flattened,y)

In [17]:
# clf.fit(x_flattened,y)

In [18]:
# import pickle
# with open('clf_3','wb') as file:
#     pickle.dump(clf,file)

In [19]:
# from sklearn.svm import SVC
# model = SVC()
# model.fit(x_flattened,y)
# model.score(x_flattened,y)

In [20]:
# with open('clf_4','wb') as file:
#     pickle.dump(model,file)

In [21]:
# from sklearn.linear_model import LogisticRegression
# clf2 = LogisticRegression()
# clf2.fit(x_flattened,y)
# clf2.score(x_flattened,y)

In [22]:
# with open('clf_5','wb') as file:
#     pickle.dump(model,file)

In [23]:
import numpy as np
x = np.array(x)
x_div = x/255

In [24]:
x_div.shape

(2311, 50, 50)

In [25]:
x_div2 = x_div.reshape(x_div.shape[0], 50, 50, 1)

In [26]:
y = np.array(y)

In [27]:
import tensorflow as tf
from tensorflow.keras import layers, models

In [28]:
model = models.Sequential([
layers.Conv2D(32, kernel_size = (3, 3), activation='relu', input_shape=(50, 50,1)),
layers.MaxPooling2D((2, 2)),
layers.Conv2D(64, (3, 3), activation='relu'),
layers.MaxPooling2D((2, 2)),    
layers.Flatten(),    
layers.Dense(64, activation='relu') ,   
layers.Dense(10,activation='softmax')
])
# model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(50, 50)))
# model.add(layers.MaxPooling2D((2, 2)))
# model.add(layers.Conv2D(64, (3, 3), activation='relu'))
# model.add(layers.MaxPooling2D((2, 2)))
# model.add(layers.Conv2D(64, (3, 3), activation='relu'))
# model.add(layers.Flatten())
# model.add(layers.Dense(64, activation='relu'))
# model.add(layers.Dense(10))
model.compile(optimizer='adam',loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),metrics=['accuracy'])
model.fit(x_div2,y, epochs=20)

Epoch 1/20
73/73 [==============================] - 10s 35ms/step - loss: 1.8043 - accuracy: 0.3690
Epoch 2/20
73/73 [==============================] - 4s 50ms/step - loss: 0.2477 - accuracy: 0.9223
Epoch 3/20
73/73 [==============================] - 3s 41ms/step - loss: 0.1000 - accuracy: 0.9787
Epoch 4/20
73/73 [==============================] - 3s 47ms/step - loss: 0.0567 - accuracy: 0.9879
Epoch 5/20
73/73 [==============================] - 4s 51ms/step - loss: 0.0222 - accuracy: 0.9953
Epoch 6/20
73/73 [==============================] - 4s 49ms/step - loss: 0.0155 - accuracy: 0.9957
Epoch 7/20
73/73 [==============================] - 3s 46ms/step - loss: 0.0180 - accuracy: 0.9955
Epoch 8/20
73/73 [==============================] - 4s 53ms/step - loss: 0.0126 - accuracy: 0.9977
Epoch 9/20
73/73 [==============================] - 4s 54ms/step - loss: 0.0050 - accuracy: 0.9992
Epoch 10/20
73/73 [==============================] - 4s 53ms/step - loss: 0.0071 - accuracy: 0.9981
Epoch 11

In [29]:
np.argmax(model.predict(x[0].reshape(1,50,50,1)/255))

0

In [30]:
# (x[0].reshape(50,50,1)/255).shape

In [31]:
x_div2.shape

(2311, 50, 50, 1)

In [32]:
# np.array(x[0].reshape(1,50,50,1)/255).shape

In [36]:
model_json = model.to_json()
with open("digits.json", "w") as json_file:
    json_file.write(model_json)
model.save_weights("digits.h5")

In [34]:
from tensorflow.keras.models import model_from_json
json_file = open('.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights("model.h5")

In [35]:
# np.argmax(loaded_model.predict(x[-100].reshape(1,50,50,1)/255))